title: IGNOU BCA Semester 3 Study Group
description: A student-led initiative for daily learning, collaboration, and growth.
author: Abhay Kumar
theme: minima
url: "https://kumarabhay1029.github.io"
baseurl: "/sem3-study-group" # if this is your repo name
